# Generated by Django 5.0.3 on 2026-03-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, help_text='Uploaded file (PDF, Word, image) — max 50MB', null=True, upload_to='submissions/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='text',
            field=models.TextField(blank=True, help_text='Written answer (optional if file uploaded)'),
        ),
    ]
