# Generated by Django 5.0.3 on 2026-03-10 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday')], max_length=3)),
                ('period', models.PositiveSmallIntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(blank=True, max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='academics.classroom')),
            ],
            options={
                'ordering': ['day', 'period'],
                'unique_together': {('class_room', 'day', 'period')},
            },
        ),
    ]
