# Generated by Django 5.0.3 on 2026-03-19 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_classroom_advisor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSubjectTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Subject this teacher teaches in this class', max_length=100)),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_teachers', to='academics.classroom')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['class_room', 'subject'],
                'unique_together': {('class_room', 'teacher', 'subject')},
            },
        ),
    ]
