# Generated by Django 5.0.3 on 2026-04-21 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_classsubjectteacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='advisor',
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='First day of the week (Sunday)')),
                ('day', models.CharField(choices=[('sun', 'Sunday'), ('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday')], max_length=3)),
                ('subject', models.CharField(max_length=100)),
                ('classwork', models.TextField(blank=True)),
                ('homework', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='academics.classroom')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['week_start', 'day', 'order'],
            },
        ),
    ]
