# Generated by Django 5.0.3 on 2026-03-15 09:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_rename_total_questions_quizattempt_total_points_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['student'], name='attempt_student_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz'], name='attempt_quiz_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['student', 'quiz'], name='attempt_student_quiz_idx'),
        ),
    ]
