# Generated by Django 5.0.3 on 2026-04-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_quizattempt_attempt_student_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
