# Generated by Django 5.0.3 on 2026-03-19 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_classroom_advisor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Date of the first day of the week (Sunday)')),
                ('week_end', models.DateField(help_text='Date of the last day of the week (Thursday)')),
                ('notes', models.TextField(blank=True, help_text='General notes for the week')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advisor', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_plans', to=settings.AUTH_USER_MODEL)),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plans', to='academics.classroom')),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('class_room', 'week_start')},
            },
        ),
        migrations.CreateModel(
            name='DailyPlanEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('sun', 'Sunday / الأحد'), ('mon', 'Monday / الاثنين'), ('tue', 'Tuesday / الثلاثاء'), ('wed', 'Wednesday / الأربعاء'), ('thu', 'Thursday / الخميس'), ('fri', 'Friday / الجمعة'), ('sat', 'Saturday / السبت')], max_length=3)),
                ('subject', models.CharField(max_length=100)),
                ('classwork', models.TextField(blank=True)),
                ('homework', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order within the day')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='lesson_plan.weeklyplan')),
            ],
            options={
                'ordering': ['day', 'order'],
            },
        ),
    ]
